apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/argoproj/argocd-example-apps.git/pre-post-sync?ref=pre-post-sync-v0.2

commonAnnotations:
  annotationKey: "1"

