apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: ubuntu:latest
        command: ["echo", "${PATH}"]
      restartPolicy: Never
  backoffLimit: 0
