apiVersion: batch/v1
kind: Job
metadata:
  generateName: my-job-
  name: my-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["sh", "-c", "sleep 5;env;exit 1"]
      restartPolicy: Never
  backoffLimit: 3
