apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: ubuntu:latest
        command: ["return", "1"]
      restartPolicy: Never
  backoffLimit: 0
