apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["sh", "-c", "sleep 5;exit 0"]
      restartPolicy: Never
  backoffLimit: 0
